spin_manifest_version = 2

[application]
name = "challenge1"
version = "0.1.0"
authors = ["David Wallace Croft <david@CroftSoft.com>"]
description = "Advent of Spin 2023 Challenge 1"

[component.data]
allowed_outbound_hosts = []
key_value_stores = ["default"]
source = "data/target/wasm32-wasi/release/challenge1.wasm"

[component.data.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
workdir = "data"

[component.spin-static-fs]
files = [{ source = "assets", destination = "/" }]
# https://github.com/fermyon/spin/issues/2112
# source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
source = "../../../spin-fileserver/target/wasm32-wasi/release/spin_static_fs.wasm"

[[trigger.http]]
route = "/data"
component = "data"

[[trigger.http]]
route = "/..."
component = "spin-static-fs"
