spin_manifest_version = 2

[application]
authors = ["David Wallace Croft <david@CroftSoft.com>"]
description = "Fermyon Advent of Spin 2023 Challenge 4"
name = "challenge4"
version = "0.1.0"

[component.bullseye]
# TODO: restrict this value
allowed_outbound_hosts = ["https://bulls-n-cows.fermyon.app"]
source = "bullseye/target/wasm32-wasi/release/bullseye.wasm"

[component.bullseye.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
workdir = "bullseye"

[[trigger.http]]
component = "bullseye"
route = "/..."
